services:
  postgres:
    image: postgres:15-alpine
    container_name: p2p-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: "backend/.env"

  redis:
    image: redis:7-alpine
    container_name: p2p-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
