FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
 && poetry install --no-dev --no-root

# Копіюємо решту проєкту
COPY . .

CMD ["uvicorn", "coordinator_main:app", "--host", "0.0.0.0", "--port", "8000"]